# Generated by Django 5.1.4 on 2025-01-09 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=47, validators=[django.core.validators.MinLengthValidator(47)])),
                ('currPlayer', models.CharField(max_length=1)),
                ('oppPlayer', models.CharField(max_length=1)),
                ('gameOver', models.BooleanField(default=False)),
            ],
        ),
    ]
